### PR TITLE
Update files.md and importing.md

### PR DESCRIPTION
**Pull request by hnvy**
Added all of the missing sections.

P.S. my apologies for creating so many pull requests. I do that to keep things as bitesize pieces for you to go through, rather than one large PR. If you would like me to create larger PRs instead, please let me know.

HR

### CODE REVIEW

**Comment by abdnh** [comment]
Thank you @hnvy!

I also prefer small PRs so no problem. I'll review them soon.

By the way, we have a Telegram group with some volunteers to coordinate translation efforts. Here's the link if you'd like to join us: https://t.me/+KCi6ASc5WtphZGNk

**Comment by hnvy** [comment]
> Thank you @hnvy!
> 
> I also prefer small PRs so no problem. I'll review them soon.
> 
> By the way, we have a Telegram group with some volunteers to coordinate translation efforts. Here's the link if you'd like to join us: https://t.me/+KCi6ASc5WtphZGNk

Thank you for your kind invite. Truly.

Regrettably, my GitHub account is currently the closest thing to social media presence I possess (along with Discord for the SuperMemo.wiki community). Nevertheless, I have bookmarked the link for future reference. In the event that I decide to create a Telegram account (which appears to host numerous educational communities), I will ensure to join the aforementioned group!

Speaking of educational communities, I have come across an open Arabic Telegram group a couple of years ago (but I am not sure if it exists anymore). It was about a book regarding memory techniques (such as [Mnemonic major system](https://en.wikipedia.org/wiki/Mnemonic_major_system)), but in Arabic! It was quite innovative; I will try to find the name of the book again as you may be interested.

Thanks again!


HR

**Comment by abdnh** [comment]
> Speaking of educational communities, I have come across an open Arabic Telegram group a couple of years ago (but I am not sure if it exists anymore). It was about a book regarding memory techniques (such as [Mnemonic major system](https://en.wikipedia.org/wiki/Mnemonic_major_system)), but in Arabic! It was quite innovative; I will try to find the name of the book again as you may be interested.

That must be this book: https://www.abdnh.net/books/alasmaaekolaha
I even wrote an experimental add-on for its mnemonic major system: https://ankiweb.net/shared/info/616438440

The Telegram group is no longer active unfortunately.

**Comment by hnvy** [comment]
> That must be this book: https://www.abdnh.net/books/alasmaaekolaha
Yes! That's the one!

I have tried to find it again online, but I wasn't able to. Such a hidden gem!


> I even wrote an experimental add-on for its mnemonic major system: https://ankiweb.net/shared/info/616438440
This is wonderful! I will try it out tomorrow.

I wanted to do the same thing (for the English mnemonic major system, and more specifically, something similar to this: mnemisis.sourceforge.net), but the limitation was time and my coding skills.

By the way, it is nice to see an Arabic-speaking person out there who is enthusiastic about learning. Very refreshing.


Thank you for what you're doing. Keep up the good work.

Best wishes,

HR

**Comment by abdnh** [comment]
Looking good!

One thing I noticed is that you're translating "note" as "ملاحظة" here and in the in-app translations. The translation I've been using so far is "ملحوظة". I don't have a strong preference to any, but it's worth being consistent with one. Let me know if you have any thoughts about this!

**Pull request merged**
